name: "thomas_dashlane"
version: "1.0.0"
config-version: 2

profile: "thomas_dashlane_profile"

model-paths: [ "models" ]
test-paths: [ "tests" ]
seed-paths: [ "data" ]
macro-paths: [ "macros" ]
snapshot-paths: [ "snapshots" ]
packages-install-path: "packages"

target-path: "target"
clean-targets:
  - "target"
  - "packages"

models:
  thomas_dashlane:
    staging:
      materialized: view
      +schema: staging

    intermediate:
      materialized: table
      +schema: intermediate

    marts:
      materialized: table
      core:
        +schema: core
      onboarding:
        +schema: onboarding


vars:
  # first date for any data at Dashlane, used to generate date spines
  default_start_date: "2022-03-14"
  # last date for any data at Dashlane (with live data it should be the current_date)
  default_end_date: "2022-04-20"
